pipeline {
    agent {
        docker {
            image 'docker:24.0.5-dind'   // גרסת docker יציבה
            args '--privileged -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    environment {
        AWS_DEFAULT_REGION = "us-east-1"
        ECR_REGISTRY = "992382545251.dkr.ecr.us-east-1.amazonaws.com"
        ECR_REPOSITORY = "oyb-status-page-app"
        IMAGE_TAG = "latest"
        APP_EC2_HOST = "ec2-user@<APP_EC2_PUBLIC_IP>"   // כתובת ה-EC2 של האפליקציה
        APP_PATH = "/home/ec2-user/status-page"         // תיקיית הפרויקט באפליקציה
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'git@github.com:oryuvbar12-max/OYB-PROJECT.git',
                    credentialsId: 'GitHub-user'
            }
        }

        stage('Install deps') {
            steps {
                sh '''
                    apk add --no-cache python3 py3-pip curl bash openssh-client
                    pip3 install awscli
                '''
            }
        }

        stage('Login to ECR') {
            steps {
                withAWS(credentials: 'aws-creds', region: "${AWS_DEFAULT_REGION}") {
                    sh '''
                        aws ecr get-login-password --region $AWS_DEFAULT_REGION | \
                        docker login --username AWS --password-stdin $ECR_REGISTRY
                    '''
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                    docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
                    docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
                '''
            }
        }

        stage('Push to ECR') {
            steps {
                sh 'docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG'
            }
        }

        stage('Deploy on EC2') {
            steps {
                script {
                    sh """
                        ssh -o StrictHostKeyChecking=no $APP_EC2_HOST '
                          cd $APP_PATH &&
                          sed -i "s|image: .*|image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|" docker-compose.yml &&
                          docker-compose pull &&
                          docker-compose up -d
                        '
                    """
                }
            }
        }
    }
}
